name: backup to gitee
on:
  workflow_call:
    secrets:
      GITEE_SYNC_TOKEN:
        required: true

jobs:
  backup-to-gitee:
    if: github.repository_owner == 'linuxdeepin'
    runs-on: ubuntu-latest
    steps:
      - name: create-repo
        run: |
          repo=${{ github.event.repository.name }}
          homepage="https://github.com/linuxdeepin/${repo}"
          description="mirror of ${homepage}"
          # remove '.' prefix
          repo=${repo#"."}
          curl -X POST --header 'Content-Type: application/json;charset=UTF-8' 'https://gitee.com/api/v5/orgs/deepin-community/repos' -d '{"public": 1,"access_token":"${{ secrets.GITEE_SYNC_TOKEN }}","name":"'"$repo"'","description":"'"$description"'","homepage":"'"$homepage"'","has_issues":"false","has_wiki":"false","can_comment":"false"}' || true
      - name: push
        run: |
          git clone --bare https://github.com/linuxdeepin/${{ github.event.repository.name }}.git .git
          repo=${{ github.event.repository.name }}
          # remove '.' prefix
          repo=${repo#"."}
          git remote set-url origin https://myml:${{ secrets.GITEE_SYNC_TOKEN }}@gitee.com/deepin-community/${repo}.git
          git push -f --all --prune origin
          git push --tags origin
