name: build linglong
on:
  workflow_call:
    secrets:
      BridgeToken:
        required: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  BRIDGE_TOKEN: ${{ secrets.BridgeToken }}
  SERVER: https://jenkins-bridge-deepin-pre.uniontech.com
  CHANGE_ID: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "PROD"
    steps:
      - name: Print Environment
        run: export

      - uses: actions/checkout@v2
        with:
          repository: "linuxdeepin/jenkins-bridge-client"
          path: jenkins-bridge-client

      - name: Install Client
        run: |
          cd $GITHUB_WORKSPACE/jenkins-bridge-client
          go build .
          sudo install -Dvm755 jenkins-bridge-client -t /usr/bin/

      - name: Trigger build
        id: generate-runid
        run: |
          echo "RUN_ID=$(jenkins-bridge-client triggerlinglong --token $BRIDGE_TOKEN)" >> $GITHUB_OUTPUT

      - name: Print log
        run: |
          jenkins-bridge-client printLog --token "$BRIDGE_TOKEN" --runid "${{ steps.generate-runid.outputs.RUN_ID }}"

      - name: cancelled post runs
        if: cancelled()
        run: |
          jenkins-bridge-client cancelBuild --token "$BRIDGE_TOKEN" --runid "${{ steps.generate-runid.outputs.RUN_ID }}"
