name: build deb
on:
  workflow_call:
    secrets:
      BridgeToken:
        required: true

env:
  GITHUB_TOKEN: ${{ github.token }}
  BRIDGE_TOKEN: ${{ secrets.BridgeToken }}
  SERVER: https://jenkins-bridge-deepin-pre.uniontech.com
  CHANGE_ID: ${{ github.event.pull_request.number }}

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment
        run: export

      - uses: actions/checkout@v2
        with:
          repository: "linuxdeepin/jenkins-bridge-client"
          path: jenkins-bridge-client

      - name: Install Client
        run: |
          cd $GITHUB_WORKSPACE/jenkins-bridge-client
          go build .
          sudo install -Dvm755 jenkins-bridge-client -t /usr/bin/

      - name: Trigger build
        id: generate-runid
        run: |
          echo "RUN_ID=$(jenkins-bridge-client triggerBuild --token $BRIDGE_TOKEN)" >> $GITHUB_OUTPUT

      - name: Print log
        run: |
          jenkins-bridge-client printLog --token "$BRIDGE_TOKEN" --runid "${{ steps.generate-runid.outputs.RUN_ID }}"

      - name: Print warning
        run: |
          echo warning on aarch64
          jenkins-bridge-client cat --server $SERVER --token "$BRIDGE_TOKEN" --file warning_aarch64.txt --runid "${{ steps.generate-runid.outputs.RUN_ID }}"
          echo warning on mips64
          jenkins-bridge-client cat --server $SERVER --token "$BRIDGE_TOKEN" --file warning_mips64.txt --runid "${{ steps.generate-runid.outputs.RUN_ID }}"
          echo warning on x86_64
          jenkins-bridge-client cat --server $SERVER --token "$BRIDGE_TOKEN" --file warning_x86_64.txt --runid "${{ steps.generate-runid.outputs.RUN_ID }}"

      - name: Download Artifacts
        continue-on-error: true
        run: |
          jenkins-bridge-client downloadArtifacts --token "$BRIDGE_TOKEN" --runid "${{ steps.generate-runid.outputs.RUN_ID }}"
          ls -lh ./artifacts

      - uses: linuxdeepin/upload-artifact@single-artifact-upload
        continue-on-error: true
        with:
          path: ./artifacts/*.deb
          single-archive: "false"

      - name: cancelled post runs
        if: cancelled()
        run: |
          jenkins-bridge-client cancelBuild --token "$BRIDGE_TOKEN" --runid "${{ steps.generate-runid.outputs.RUN_ID }}"
