name: commitlint
on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download commitlint config teamplate
        run: |
          wget https://raw.githubusercontent.com/linuxdeepin/.github/master/commitlint/commitlint.config.js \
            -O ./commitlint.config.js

      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: "./commitlint.config.js"
